[project]
name = "merfish-sqi"
version = "0.1.0"
requires-python = ">=3.9"
dependencies = [
  "numpy",
  "scipy",
  "scikit-image",
  "matplotlib",
  "tifffile",
  "zarr",
  "cellpose"
]

[tool.setuptools]
packages = ["sqi", "segmentation"]
